dataArray = [
	
	{
		icon: '🗿',
		type: '結界',
		x: 25,
		y: 125,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '赤門',
		x: 25,
		y: 115,
		date: '2021年3月12日',
		comment: '近いところに赤いスーパーがふたつ',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '街中華',
		x: 25,
		y: 105,
		date: '2021年5月3日',
		comment: '行きつけ中華',
		image: 'adamski.jpg',
		GeolocationPosition: '',		
	},

	{
		icon: '🗿',
		type: '二枚貝',
		x: 25,
		y: 90,
		date: '2021年6月10日',
		comment: '玄関でお出迎え',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: 'NHK',
		x: 25,
		y: 75,
		date: '2021年6月19日',
		comment: 'どっかでみたことのあるキャラクター',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 25,
		y: 55,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		type: '結界',
		x: 50,
		y: 50,
		date: '2021年2月25日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

];