dataArray = [
	// 一層目
	{
		icon: '🗼',
		rarelity:'⭐︎',
		type: '青い塔',
		x: 50,
		y: 90,
		date: '2023年7月11日',
		comment: '市ヶ谷では珍しいカラフルなオブジェ',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/WXvmspVWJ4AwB3jG8',
	},

	{
		icon: '🌳',
		rarelity:'⭐︎',
		type: 'グリーンロード',
		x: 50,
		y: 85,
		date: '2023年7月11日',
		comment: 'おとぎ話に誘われそう',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/ZJQmoX3PtmPuzGLf9',
	},

	{
		icon: '🧻',
		rarelity:'⭐︎',
		type: '切り絵',
		x: 50,
		y: 80,
		date: '2023年7月11日',
		comment: '紙が切り貼りしてるみたい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/1wntcm7nHPtqQhZU7',		
	},

	{
		icon: '💩',
		rarelity:'⭐︎',
		type: 'ｳ○ﾁ',
		x: 50,
		y: 75,
		date: '2023年7月11日',
		comment: 'デュシャンの泉についてるｳ○ﾁ',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/PcrSounvAnkKntx69',
	},

	{
		icon: '🚬',
		rarelity:'⭐︎',
		type: 'たばこ',
		x: 50,
		y: 70,
		date: '2023年7月11日',
		comment: 'たばこは売ってないよ。(´∀｀)アサヒ',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/L6ZMcWpLhs5Tm7249',
	},

	{
		icon: '📻',
		rarelity:'⭐︎',
		type: '昭和',
		x: 50,
		y: 65,
		date: '2023年7月11日',
		comment: 'ジブリとかに出てきそう',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/vsiLbGqyWVVkMDfK6',
	},

	{
		icon: '🔥',
		rarelity:'⭐︎',
		type: 'メラメラ',
		x: 50,
		y: 60,
		date: '2023年7月11日',
		comment: '炎が風に揺られている',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/uskHEQPu6NpvCdPn8',
	},

	{
		icon: '⛓',
		rarelity:'⭐︎',
		type: '鉄格子',
		x: 50,
		y: 55,
		date: '2023年7月11日',
		comment: '電気とか走ってる？',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/L6XF9h8A59shyqNU9',
	},

	{
		icon: '🛹',
		rarelity:'⭐︎',
		type: '二人乗りスケートボーダー',
		x: 50,
		y: 50,
		date: '2023年7月11日',
		comment: '親子で仲良く二人乗り',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/FKSs96Mz9s8a2Pif9',
	},

	{
		icon: '🐻',
		rarelity:'⭐︎',
		type: 'しろくま',
		x: 50,
		y: 45,
		date: '2023年7月11日',
		comment: '自販機の中に一瞬入りたい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/qJeYuffwne6CpZnz7',
	},

	{
		icon: '🪵',
		rarelity:'⭐︎',
		type: '肩身が狭い木',
		x: 50,
		y: 40,
		date: '2023年7月11日',
		comment: '建物と電線に囲まれて細々と生きてます',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/7dM3TyoAs6Ho8FKH7',
	},

	{
		icon: '🍜',
		rarelity:'⭐︎',
		type: '十割蕎麦',
		x: 50,
		y: 45,
		date: '2023年7月11日',
		comment: '何が十割！？',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/CCoMNRe1KYAhvkTo8',
	},

	{
		icon: '🍀',
		rarelity:'⭐︎',
		type: '円陣',
		x: 50,
		y: 35,
		date: '2023年7月11日',
		comment: '奉納されてるみたい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/BxibNuvZz5dUYrzFA',
	},

	{
		icon: '💩',
		rarelity:'⭐︎',
		type: 'ｳ●ﾁ',
		x: 50,
		y: 30,
		date: '2023年7月11日',
		comment: 'これはもうそれ',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/duvGaUE9eZQ8Ymvc7',
	},

	{
		icon: '🇰🇷',
		rarelity:'⭐︎',
		type: '韓国街',
		x: 50,
		y: 27,
		date: '2023年7月11日',
		comment: '高校周辺の看板が全部韓国語',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/cxtP18PMXpS6xHPg7',
	},

	{
		icon: '🧺',
		rarelity:'⭐︎',
		type: '籠ホーム',
		x: 55,
		y: 27,
		date: '2023年7月11日',
		comment: '老人ホームには見えない',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/AKL8VgS8DhtMb8hFA',
	},

	{
		icon: '🚲',
		rarelity:'⭐︎',
		type: '二輪',
		x: 58,
		y: 27,
		date: '2023年7月11日',
		comment: '駐輪はしてないけど',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/nbyF36izqxJKMQTV9',
	},

	{
		icon: '🐚',
		rarelity:'⭐︎',
		type: '二枚貝',
		x: 63,
		y: 25,
		date: '2023年7月11日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/YToeVNYAPxQNkPADA',
	},

	{
		icon: '🚲',
		rarelity:'⭐︎',
		type: '寄生された二輪車',
		x: 63,
		y: 22,
		date: '2023年7月11日',
		comment: '土には還らない',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/mZtQw1APNxMMiLJZ9',
	},

	{
		icon: '🐟',
		rarelity:'⭐︎',
		type: 'うなぎ',
		x: 67,
		y: 27,
		date: '2023年7月11日',
		comment: '店名は無いけどうなぎを焼いてますい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/Ua8rsRvkH7BbFedZ9',
	},

	{
		icon: '📮',
		rarelity:'⭐︎',
		type: '自家製郵便ポスト',
		x: 70,
		y: 27,
		date: '2023年7月11日',
		comment: 'なぜ自宅ポストに郵便マークが！？',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/HoB6awPLXfUwuT4o7',
	},

	{
		icon: '🪧',
		rarelity:'⭐︎',
		type: 'アーバンプレイス',
		x: 75,
		y: 27,
		date: '2023年7月11日',
		comment: 'ちょっとダサい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/WUZumQMUXdbtcYoQA',
	},

	{
		icon: '🪧',
		rarelity:'⭐︎⭐︎⭐︎',
		type: 'フラットジョイ',
		x: 78,
		y: 27,
		date: '2023年7月11日',
		comment: '意味わからん',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/9so5ZVURnuM5YuyD9',
	},

	{
		icon: '📫',
		rarelity:'⭐︎',
		type: 'デンデンムシ',
		x: 79,
		y: 34,
		date: '2023年7月11日',
		comment: 'かわいい',
		image: 'adamski.jpg',
		GeolocationPosition: 'https://goo.gl/maps/xH9zV1k5UCe7mqo6A',
	},

	{
		icon: '🧩',
		rarelity:'⭐︎',
		type: '応急処置',
		x: 77,
		y: 34,
		date: '2023年7月11日',
		comment: '違和感',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🦉',
		rarelity:'⭐︎',
		type: 'フクロウショップ',
		x: 72,
		y: 40,
		date: '2023年7月11日',
		comment: 'ドアがかわいい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🍖',
		rarelity:'⭐︎',
		type: '沈黙の肉',
		x: 72,
		y: 37,
		date: '2023年7月11日',
		comment: 'どゆこと',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🔮',
		rarelity:'⭐︎',
		type: 'ダブルビンゴ',
		x: 72,
		y: 47,
		date: '2023年7月11日',
		comment: 'ビンゴしまくり',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🏠',
		rarelity:'⭐︎',
		type: 'ひょろなが邸',
		x: 70,
		y: 47,
		date: '2023年7月11日',
		comment: '細いなー',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '👍',
		rarelity:'⭐︎',
		type: '指紋(門)',
		x: 60,
		y: 65,
		date: '2023年7月11日',
		comment: '指紋みたいな門',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🏛',
		rarelity:'⭐︎',
		type: 'ポーラ美術館',
		x: 55,
		y: 70,
		date: '2023年7月11日',
		comment: '写真で見た美術館を想起する',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🍟',
		rarelity:'⭐︎',
		type: 'ぽってっとポテチ',
		x: 55,
		y: 75,
		date: '2023年7月11日',
		comment: 'ポテチのバッグがポツンと',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🐿',
		rarelity:'⭐︎',
		type: 'ハム三郎',
		x: 55,
		y: 77,
		date: '2023年7月11日',
		comment: 'お休み',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},


	// 二層目
	{
		icon: '⛩',
		rarelity:'⭐︎',
		type: '赤門',
		x: 38,
		y: 35,
		date: '2023年7月5日',
		comment: 'まいばすけっとがすぐ近くに2軒',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '⛩',
		rarelity:'⭐︎',
		type: '赤門',
		x: 33,
		y: 35,
		date: '2023年7月5日',
		comment: 'まいばすけっとがすぐ近くに2軒',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🚧',
		rarelity:'⭐︎',
		type: 'ガードパック',
		x: 18,
		y: 35,
		date: '2023年7月5日',
		comment: '大量のガードレール',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '👹',
		rarelity:'⭐︎',
		type: '守り神',
		x: 19,
		y: 45,
		date: '2023年7月5日',
		comment: '悪い奴はいねえか〜',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🚪',
		rarelity:'⭐︎',
		type: 'ドラえもん',
		x: 20,
		y: 55,
		date: '2023年7月5日',
		comment: 'ドラえもんの色にしか見えない',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🌱',
		rarelity:'⭐︎',
		type: 'もじゃもじゃ',
		x: 20,
		y: 70,
		date: '2023年7月5日',
		comment: '倉庫にもじゃッと',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},


	//三層目
	{
		icon: '🥢',
		rarelity:'⭐︎',
		type: 'CI行きつけ中華',
		x: 45,
		y: 80,
		date: '2023年6月28日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🏯',
		rarelity:'⭐︎',
		type: '鉄壁',
		x: 45,
		y: 55,
		date: '2023年6月28日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🗿',
		rarelity:'⭐︎',
		type: '結界',
		x: 60,
		y: 55,
		date: '2023年6月28日',
		comment: '敷地の四方に石があって結界みたい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '⛰',
		rarelity:'⭐︎',
		type: '洞窟',
		x: 68,
		y: 55,
		date: '2023年6月28日',
		comment: 'オレンジの洞窟',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🎐',
		rarelity:'⭐︎',
		type: '風の通り道',
		x: 78,
		y: 65,
		date: '2023年6月28日',
		comment: '涼しい',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

	{
		icon: '🐰',
		rarelity:'⭐︎',
		type: 'NHK',
		x: 61,
		y: 65,
		date: '2023年6月28日',
		comment: 'どっかで見たことある',
		image: 'adamski.jpg',
		GeolocationPosition: '',
	},

];